<?php
	/**
	 * @var array      $list
	 * @var string     $name
	 * @var string     $title
	 * @var string[]   $fields
	 * @var callable[] $templates
	 */
?>
<div class="panel panel-default">
	<div id="<?= $name ?>>" class="panel-heading" role="tab">
		<h4 class="panel-title">
			<a href="#<?= $name ?>-body" role="button" data-toggle="collapse" data-parent="#accordion" aria-expanded="true" aria-controls="<?= $name ?>-body"><?= $title ?></a>
			<span class="badge"><?= count($list) ?></span>
		</h4>
	</div>
	<div id="<?= $name ?>-body" class="panel-collapse collapse" role="tabpanel">
		<input class="search form-control" placeholder="Поиск" />
		<table class="table table-condensed table-hover">
			<thead>
			<?php
				$i = 0;
			?>
			<tr>
				<?php foreach ($fields as $f_title => $field) { ?>
					<th>

						<?php if(++$i > 1) { ?>
							<button class="sort btn btn-info btn-xs" data-sort="filter-<?= $i ?>"></button>
						<?php } ?>
						<?= $f_title ?>
					</th>
				<?php } ?>
			</tr>
			</thead>
			<tbody class="list">
			<?php foreach ($list as $segment) { ?>
				<?php
					$i = 0;
				?>
				<tr>
					<?php foreach ($fields as $field) { ?>
						<td class="filter-<?= ++$i ?>">
							<?= is_callable($field) ? call_user_func($field, $segment) : (isset($templates[$field]) ? call_user_func($templates[$field], $segment) : $segment[$field]) ?>
						</td>
					<?php } ?>
				</tr>
			<?php } ?>
			</tbody>
		</table>
		<?php
			//- @area.segments.lock_level(@editor_level).drivable.disconnected.order('dc_density desc').each do |segment|
		?>
	</div>
</div>