<?php
	/** @var string $raw_coordinates */
?>
<script>
	function coordinates (){
		return <?= $raw_coordinates ?>;
	}
</script>
<div id="map" style="width:100%; height:800px"></div>
<div>Привязки последнего бокса:
	<label><input type="checkbox" id="north">север</label>
	<label><input type="checkbox" id="east">восток</label>
	<label><input type="checkbox" id="south">юг</label>
	<label><input type="checkbox" id="west">запад</label>
	<button id="fixed">Установит привязки</button>
</div>
<button id="render">Загрузить из списка</button>
<button id="save">Создать список</button>
<button id="add">Добавить клон последнего</button>
<textarea id="list" rows="10" style="width:100%">20.8,55.3,21.07,55.21
</textarea>
