<?php
	/**
	 * array $areas
	 */
?>
<h3 class="text-center">Настройки</h3>
<div class="alert alert-warning alert-dismissible" role="alert">
	<button class="close" data-dismiss="alert" aria-label="Fechar">
		<span aria-hidden="true"></span>&times;
	</button>
	<strong>Внимание</strong>Настройки работают только в браузерах с поддержкой cookie!<br>
	Кроме того, они действительны только для этого компьютера и этого браузера. Если вы используете несколько компьютеров или браузеров, просто повторите процесс в любом из них
</div>

<form class="form-horizontal settings-form">
	<div class="form-group">
		<label class="col-sm-4 col-md-3 col-lg-2 control-label">WME</label>
		<div class="col-sm-8 col-md-9 col-lg-10">
			<select name="wme_url" class="form-control">
				<option value="https://www.waze.com/">Стандатный</option>
				<option value="https://editor-beta.waze.com/">Бета</option>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-4 col-md-3 col-lg-2 control-label">Уровень редактора</label>
		<div class="col-sm-8 col-md-9 col-lg-10">
			<select class="form-control" name="editor_level">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
				<option value="6">6</option>
			</select>
		</div>

	</div>
	<button class="btn btn-primary" type="submit">Сохранить</button>
</form>
